#spring.cloud.config.label 指明远程仓库的分支
spring:
  application:
    name: config-client
  cloud:
  #spring.cloud.config.profile
  #dev开发环境配置文件
  #test测试环境
  #pro正式环境
    config:
      label: master
      profile: dev
      #第一种方式 通过ip读取
      #uri: http://localhost:8888/

      #第二种方式 从配置中心通过服务名读取文件
      discovery:
        enabled: true
        service-id: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8882

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
