#spring.cloud.config.label 指明远程仓库的分支
spring:
  application:
    name: config-client
  cloud:
  #spring.cloud.config.profile
  #dev开发环境配置文件
  #test测试环境
  #pro正式环境
    config:
      label: master
      profile: dev
      #第一种方式 通过ip读取
      #uri: http://localhost:8888/

      #第二种方式 从配置中心通过服务名读取文件
      discovery:
        enabled: true
        service-id: config-server
server:
  port: 8881

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
