spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

#以/api-a/ 开头的请求都转发给service-ribbon服务；以/api-b/开头的请求都转发给service-feign服务；
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon

    api-b:
      path: /api-b/**
      serviceId: service-feign


