---
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://peer2:8769/eureka/
spring:
  profiles: peer1

#---
#server:
#  port: 8769
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://peer1:8761/eureka/
#spring:
#  profiles: peer2