server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-feign
  #抽样配置 默认0.1 十次上传一次
  sleuth:
    sampler:
      probability: 0.5
  #全链路追踪监控 配置服务端地址
  zipkin:
    base-url: http://localhost:9411

feign:
  hystrix:
    enabled: true

app:
  id: public
apollo:
  meta: http://47.100.233.192:8080
  bootstrap:
    namespaces: TEST1.Feign-config
    eagerLoad:
      enabled=true: