server:
  port: 8889
spring:
  application:
    name: qrcode
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
    bus:
      refresh:
        enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#QR:
#  content: https://github.com/fengliao/SpringCloudDemo
#  imgPath: D:\我的文档\My Pictures\Who Wishes Dawn.jpg
#  destPath: E:\迅雷下载\
